layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: trevor-laher-366128b0
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

products:
  - name: Sway Points
    web_url: https://swaypoints.com
    image_url: https://swaypoints.com/img/slackpoints-graphic-1000px.png
    description: A Slack tool to make your vote count.

topics:
  - name: Hiking
    web_url: /hiking
    image_url: https://www.pngitem.com/pimgs/m/76-761645_transparent-clipart-montagne-mountain-icon-hd-png-download.png

  - name: Cloud Computing
    web_url: /cloud
    image_url: https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcR3MXMnRVtUvQLkjXKjvYgGgSH7ZcDellpgXZSLs7MSdykCARIu

  - name: Books
    web_url: /books

  - name: Music
    web_url: /music

  - name: Video Games
    web_url: /videoGames

  - name: Film
    web_url: /film